name: Run Unit Tests

on: [push]

jobs:
 unit-tests:
  name: Run Unit Tests
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4.1.0
   - uses: actions/setup-node@v3.8.1
     with: 
      node-version: 18
      cache: 'npm'
   - run: npm ci
   - run: npm run test
